version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_andre
    network_mode: host 
    tty: true
    #ports:
    #  - "5000:5000"

    

    environment:
      CONFIGURATION_SETUP: rfactorapp.config.DevelopmentConfig
    
    #volumes:
    #  - ./rfactor/:/usr/src/app/
    